name: House of Bogue
favicon: null
layout_spectrum: 0.49001540220342577
typography_spectrum: 0.971815591910854
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8701419848948717
  lightness: 0.20115126413293183
  saturation: 0.6986440427135676
  rhythmicContrast: 0.2849934690166265
purpose: []
